server:
    port: 9000

spring:
    application:
        name: gateway

    cloud:
        gateway:
          default-filter:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10 #how many tokens will it put into pocket per second
                  burstCapacity: 20 #total capacity
                  requestedToken: 1 #one token for each request
          routes:
            - id: auth-route
              uri: http://localhost:9001
              predicates:
                  - Path=/api/v1/auth/**
              filters:
                - AddRequestHeader=X-Tenant,acme
                - AddResponseHeader=x-Genre,fantasy
                - name: Retry
                  args:
                    retries: 3
                    method: GET
                    backoff:
                      firstBackoff: 500ms
                      maxBackoff: 500ms